version: "3"
services:
  mc:
    image: itzg/minecraft-server
    volumes:
    - ./modpacks:/modpacks:ro
    - data:/data
    environment:
      EULA: "true"
      TYPE: AUTO_CURSEFORGE
      CF_PAGE_URL: https://legacy.curseforge.com/minecraft/modpacks/newtcraft-1-20-1
      MEMORY: "6G"
      TZ: "America/California"
      OVERRIDE_SERVER_PROPERTIES: "true"
      DIFFICULTY: "hard"
      MAX_TICK_TIME: "-1"
      ALLOW_FLIGHT: "true"
      OPS: "CalculousNewt63"
      VIEW_DISTANCE: 10
      MAX_PLAYERS: 10
      PVP: "true"
      MOTD: "A Create Focused Minecraft Server"
      ENFORCE_WHITELIST: "true"
      ENABLE_WHITELIST: "true"
      WHITELIST: "CalculousNewt63,Polyca"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: true
      SPAWN_PROTECTION: 50
      SEED: "shiddingnfarding"
      SERVER_NAME: NewtCraft

    ports:
      - "25565:25565"
    restart: unless-stopped

volumes:
  data: {}
