version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
  #  command: --mapping=mc.newt-craft.com=192.168.0.46:25565
      
    environment:
      EULA: "true"
      MOD_PLATFORM: AUTO_CURSEFORGE
      # allocate from https://console.curseforge.com/ and set in .env file
      CF_API_KEY: "/home/calculousnewt63/.env"
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/newtcraft-1-20-1/files/5098257
      
      
  #    CF_EXCLUDE_MODS: |
  #      itemphysiclite

      # Optional: select a specific version/file
      #CF_FILENAME_MATCHER: "0.2.34"
      MEMORY: 24G
    volumes:
      - mc-data:/data
      - ./downloads:/downloads

volumes:
  mc-data: {}
