version: "3.8"

services:
  mc:
    image: itzg/minecraft-server:java17@sha256:e7303b72c9ce40ef6e0df4287ff517ab6380d1108dcf4fa285bdb95623b4be00
    environment:
      EULA: "true"
    ports:
      - "25565:25565"
    volumes:
      - data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  data: {}
